routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@getIndex')->name('home');
Route::get('login', 'Auth\LoginController@getNewReply');
Auth::routes(['verify' => true]);

# BROWSE
require_once __DIR__.'/lorekeeper/browse.php';

/**************************************************************************************************
    Routes that require login
**************************************************************************************************/
Route::group(['middleware' => ['auth', 'verified']], function() {

    # LINK DA ACCOUNT
    Route::get('/link', 'HomeController@getLink')->name('link');
    
    Route::get('/auth/redirect/{driver}', 'HomeController@getAuthRedirect');
    Route::get('/auth/callback/{driver}', 'HomeController@getAuthCallback');

    # SET BIRTHDATE
    Route::get('/birthday', 'HomeController@getBirthday')->name('birthday');
    Route::post('/birthday', 'HomeController@postBirthday');

    Route::get('/blocked', 'HomeController@getBirthdayBlocked')->name('blocked');

    # BANNED
    Route::get('banned', 'Users\AccountController@getBanned');

    /**********************************************************************************************
        Routes that require having a linked dA account (also includes blocked routes when banned)
    **********************************************************************************************/
    Route::group(['middleware' => ['alias']], function() {

        require_once __DIR__.'/lorekeeper/members.php';

        /**********************************************************************************************
            Admin panel routes
        **********************************************************************************************/
        Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['staff']], function() {

            require_once __DIR__.'/lorekeeper/admin.php';

        });
    });
});

app/Models/Character/CharacterAward.php
<?php

namespace App\Models\Character;

use App\Models\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CharacterAward extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'data', 'award_id', 'character_id'
    ];

    /**
     * Whether the model contains timestamps to be saved and updated.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'character_awards';

    /**********************************************************************************************
    
        RELATIONS

    **********************************************************************************************/

    /**
     * Get the character who owns the stack.
     */
    public function character() 
    {
        return $this->belongsTo('App\Models\Character\Character');
    }

    /**
     * Get the item associated with this item stack.
     */
    public function award() 
    {
        return $this->belongsTo('App\Models\Award\Award');
    }

    /**********************************************************************************************
    
        ACCESSORS

    **********************************************************************************************/

    /**
     * Get the data attribute as an associative array.
     *
     * @return array
     */
    public function getDataAttribute() 
    {
        return json_decode($this->attributes['data'], true);
    }
    
    /**
     * Checks if the stack is transferrable.
     *
     * @return array
     */
    public function getIsTransferrableAttribute()
    {
        if(!isset($this->data['disallow_transfer']) && $this->award->allow_transfer) return true;
        return false;
    }

    /**
     * Gets the available quantity of the stack.
     *
     * @return int
     */
    public function getAvailableQuantityAttribute()
    {
        return ($this->count);
    }

    /**
     * Gets the stack's asset type for asset management.
     *
     * @return string
     */
    public function getAssetTypeAttribute()
    {
        return 'character_awards';
    }
}

app/Models/Character/CharacterDesignUpdate.php
<?php

namespace App\Models\Character;

use Config;
use DB;
use App\Models\Model;
use App\Models\Currency\Currency;
use App\Models\Feature\FeatureCategory;
use Illuminate\Database\Eloquent\SoftDeletes;

class CharacterDesignUpdate extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'character_id', 'status', 'user_id', 'staff_id',
        'comments', 'staff_comments', 'data', 'extension',
        'use_cropper', 'x0', 'x1', 'y0', 'y1',
        'hash', 'species_id', 'subtype_id', 'rarity_id',
        'has_comments', 'has_image', 'has_addons', 'has_features',
        'submitted_at', 'update_type', 'fullsize_hash', 
        'approval_votes', 'rejection_votes'
    ];

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'design_updates';

    /**
     * Whether the model contains timestamps to be saved and updated.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * Dates on the model to convert to Carbon instances.
     *
     * @var array
     */
    public $dates = ['submitted_at'];

    /**
     * Validation rules for uploaded images.
     *
     * @var array
     */
    public static $imageRules = [
        'image' => 'nullable|mimes:jpeg,gif,png',
        'thumbnail' => 'nullable|mimes:jpeg,gif,png',
        'artist_url.*' => 'nullable|url',
        'designer_url.*' => 'nullable|url'
    ];

    /**********************************************************************************************

        RELATIONS

    **********************************************************************************************/

    /**
     * Get the character associated with the design update.
     */
    public function character()
    {
        return $this->belongsTo('App\Models\Character\Character', 'character_id');
    }

    /**
     * Get the user who created the design update.
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User\User', 'user_id');
    }

    /**
     * Get the staff who processed the design update.
     */
    public function staff()
    {
        return $this->belongsTo('App\Models\User\User', 'staff_id');
    }

    /**
     * Get the species of the design update.
     */
    public function species()
    {
        return $this->belongsTo('App\Models\Species\Species', 'species_id');
    }

    /**
     * Get the subtype of the design update.
     */
    public function subtype()
    {
        return $this->belongsTo('App\Models\Species\Subtype', 'subtype_id');
    }

    /**
     * Get the rarity of the design update.
     */
    public function rarity()
    {
        return $this->belongsTo('App\Models\Rarity', 'rarity_id');
    }

    /**
     * Get the features (traits) attached to the design update, ordered by display order.
     */
    public function features()
    {
        $ids = FeatureCategory::orderBy('sort', 'DESC')->pluck('id')->toArray();

        $query = $this->hasMany('App\Models\Character\CharacterFeature', 'character_image_id')->where('character_features.character_type', 'Update')->join('features', 'features.id', '=', 'character_features.feature_id')->select(['character_features.*', 'features.*', 'character_features.id AS character_feature_id']);

        return count($ids) ? $query->orderByRaw(DB::raw('FIELD(features.feature_category_id, '.implode(',', $ids).')')) : $query;
    }

    /**
     * Get the features (traits) attached to the design update with no extra sorting.
     */
    public function rawFeatures()
    {
        return $this->hasMany('App\Models\Character\CharacterFeature', 'character_image_id')->where('character_features.character_type', 'Update');
    }

    /**
     * Get the designers attached to the design update.
     */
    public function designers()
    {
        return $this->hasMany('App\Models\Character\CharacterImageCreator', 'character_image_id')->where('type', 'Designer')->where('character_type', 'Update');
    }

    /**
     * Get the artists attached to the design update.
     */
    public function artists()
    {
        return $this->hasMany('App\Models\Character\CharacterImageCreator', 'character_image_id')->where('type', 'Artist')->where('character_type', 'Update');
    }

    /**********************************************************************************************

        SCOPES

    **********************************************************************************************/

    /**
     * Scope a query to only include active (Open or Pending) update requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('status', '!=', 'Approved')->where('status', '!=', 'Rejected');
    }

    /**
     * Scope a query to only include MYO slot approval requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeMyos($query)
    {
        $query->select('design_updates.*')->where('update_type', 'MYO');
    }

    /**
     * Scope a query to only include character design update requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCharacters($query)
    {
        $query->select('design_updates.*')->where('update_type', 'Character');
    }

    /**********************************************************************************************

        ACCESSORS

    **********************************************************************************************/

    /**
     * Get the data attribute as an associative array.
     *
     * @return array
     */
    public function getDataAttribute()
    {
        return json_decode($this->attributes['data'], true);
    }

    /**
     * Get the items (UserItem IDs) attached to this update request.
     *
     * @return array
     */
    public function getInventoryAttribute()
    {
        // This is for showing the addons page
        // just need to retrieve a list of stack IDs to tell which ones to check

        return $this->data && isset($this->data['user']['user_items']) ? $this->data['user']['user_items'] : [];
    }

    /**
     * Get the user-owned currencies attached to this update request.
     *
     * @return array
     */
    public function getUserBankAttribute()
    {
        return $this->data && isset($this->data['user']['currencies']) ? $this->data['user']['currencies'] : [];
    }

    /**
     * Get the character-owned currencies attached to this update request.
     *
     * @return array
     */
    public function getCharacterBankAttribute()
    {
        return $this->data && isset($this->data['character']['currencies']) ? $this->data['character']['currencies'] : [];
    }

    /**
     * Check if all sections of the form have been touched.
     *
     * @return bool
     */
    public function getIsCompleteAttribute()
    {
        return ($this->has_comments && $this->has_image && $this->has_addons && $this->has_features);
    }

    /**
     * Gets the file directory containing the model's image.
     *
     * @return string
     */
    public function getImageDirectoryAttribute()
    {
        return 'images/character-updates/'.floor($this->id / 1000);
    }

    /**
     * Gets the file name of the model's image.
     *
     * @return string
     */
    public function getImageFileNameAttribute()
    {
        return $this->id . '_'.$this->hash.'.'.$this->extension;
    }

    /**
     * Gets the path to the file directory containing the model's image.
     *
     * @return string
     */
    public function getImagePathAttribute()
    {
        return public_path($this->imageDirectory);
    }

    /**
     * Gets the URL of the model's image.
     *
     * @return string
     */
    public function getImageUrlAttribute()
    {
        return asset($this->imageDirectory . '/' . $this->imageFileName);
    }

    /**
     * Gets the file name of the model's thumbnail image.
     *
     * @return string
     */
    public function getThumbnailFileNameAttribute()
    {
        return $this->id . '_'.$this->hash.'_th.'.$this->extension;
    }

    /**
     * Gets the path to the file directory containing the model's thumbnail image.
     *
     * @return string
     */
    public function getThumbnailPathAttribute()
    {
        return $this->imagePath;
    }

    /**
     * Gets the URL of the model's thumbnail image.
     *
     * @return string
     */
    public function getThumbnailUrlAttribute()
    {
        return asset($this->imageDirectory . '/' . $this->thumbnailFileName);
    }

    /**
     * Gets the URL of the design update request.
     *
     * @return string
     */
    public function getUrlAttribute()
    {
        return url('designs/'.$this->id);
    }

    /**
     * Gets the voting data of the design update request.
     *
     * @return string
     */
    public function getVoteDataAttribute()
    {
        return collect(json_decode($this->attributes['vote_data'], true));
    }

    /**********************************************************************************************

        OTHER FUNCTIONS

    **********************************************************************************************/

    /**
     * Get the available currencies that the user can attach to this update request.
     *
     * @param  string  $type
     * @return array
     */
    public function getBank($type)
    {
        if($type == 'user') $currencies = $this->userBank;
        else $currencies = $this->characterBank;
        if(!count($currencies)) return [];
        $ids = array_keys($currencies);
        $result = Currency::whereIn('id', $ids)->get();

app/Http/Controllers/Admin/Characters/GrantController.php
<?php

namespace App\Http\Controllers\Admin\Characters;

use Auth;
use Config;
use Illuminate\Http\Request;

use App\Models\Character\Character;
use App\Models\Currency\Currency;
use App\Models\Item\Item;

use App\Services\CurrencyManager;
use App\Services\InventoryManager;
use App\Services\AwardCaseManager;

use App\Http\Controllers\Controller;

class GrantController extends Controller
{
    /**
     * Grants or removes currency from a character.
     *
     * @param  string                        $slug
     * @param  \Illuminate\Http\Request      $request
     * @param  App\Services\CurrencyManager  $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postCharacterCurrency($slug, Request $request, CurrencyManager $service)
    {
        $data = $request->only(['currency_id', 'quantity', 'data']);
        if($service->grantCharacterCurrencies($data, Character::where('slug', $slug)->first(), Auth::user())) {
            flash('Currency granted successfully.')->success();
        }
        else {
            foreach($service->errors()->getMessages()['error'] as $error) flash($error)->error();
        }
        return redirect()->back();
    }

    /**
     * Grants items to characters.
     *
     * @param  string                          $slug
     * @param  \Illuminate\Http\Request        $request
     * @param  App\Services\InventoryManager   $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postCharacterItems($slug, Request $request, InventoryManager $service)
    {
        $data = $request->only(['item_ids', 'quantities', 'data', 'disallow_transfer', 'notes']);
        if($service->grantCharacterItems($data,  Character::where('slug', $slug)->first(), Auth::user())) {
            flash('Items granted successfully.')->success();
        }
        else {
            foreach($service->errors()->getMessages()['error'] as $error) flash($error)->error();
        }
        return redirect()->back();
    }

    /**
     * Grants awards to characters.
     *
     * @param  string                          $slug
     * @param  \Illuminate\Http\Request        $request
     * @param  App\Services\InventoryManager   $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postCharacterAwards($slug, Request $request, AwardCaseManager $service)
    {
        $data = $request->only(['award_ids', 'quantities', 'data', 'disallow_transfer', 'notes']);
        if($service->grantCharacterAwards($data,  Character::where('slug', $slug)->first(), Auth::user())) {
            flash('Awards granted successfully.')->success();
        }
        else {
            foreach($service->errors()->getMessages()['error'] as $error) flash($error)->error();
        }
        return redirect()->back();
    }
}

resources/views/character/design/_confirm_modal.blade.php
@if($request->user_id == Auth::user()->id)
    @if($request->isComplete)
        <p>This will submit the design approval request. While the request is in the queue, <u>you will not be able to edit it</u>. </p>
        <p>Are you sure you want to submit this request?</p>
        {!! Form::open(['url' => 'designs/'.$request->id.'/submit', 'class' => 'text-right']) !!}
            {!! Form::submit('Submit Request', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
    @else
        <p class="text-danger">Not all sections have been completed yet. Please visit the necessary tab(s) and click Save to update them, even if no modifications to the information are needed.</p>
        <div class="text-right">
            <button class="btn btn-primary" disabled>Submit Request</button>
        </div>
    @endif
@else 
    <div>You cannot submit this request.</div>
@endif

resources/views/character/design/_delete_modal.blade.php
@if($request->user_id == Auth::user()->id)
    @if($request->status == 'Draft')
        <p>This will delete the request and return all attached items/currency to you. </p>
        <p>Are you sure you want to delete this request?</p>
        {!! Form::open(['url' => 'designs/'.$request->id.'/delete', 'class' => 'text-right']) !!}
            {!! Form::submit('Delete Request', ['class' => 'btn btn-danger']) !!}
        {!! Form::close() !!}
    @else
        <p class="text-danger">This request has already been submitted to the queue and cannot be deleted.</p>
    @endif
@else 
    <div>You cannot delete this request.</div>
@endif

resources/views/character/design/_features_subtype.blade.php
{!! Form::select('subtype_id', $subtypes, $subtype, ['class' => 'form-control', 'id' => 'subtype']) !!}

resources/views/character/design/_header.blade.php
<h1>
    Request (#{{ $request->id }}): {!! $request->character ? $request->character->displayName : 'Deleted Character [#'.$request->character_id.']' !!}
    <span class="float-right badge badge-{{ ($request->status == 'Draft' || $request->status == 'Pending') ? 'secondary' : ($request->status == 'Approved' ? 'success' : 'danger') }}">{{ $request->status }}
</h1>

@if(isset($request->staff_id))
    @if($request->staff_comments && ($request->user_id == Auth::user()->id || Auth::user()->hasPower('manage_submissions')))
        <h5 class="text-danger">Staff Comments ({!! $request->staff->displayName !!})</h5>
        <div class="card border-danger mb-3"><div class="card-body">{!! nl2br(htmlentities($request->staff_comments)) !!}</div></div>
    @else
        <p>No staff comment was provided.</p>
    @endif
@endif

@if($request->status != 'Draft' && Auth::user()->hasPower('manage_characters') && Config::get('lorekeeper.extensions.design_update_voting'))
    <?php
        $rejectSum = 0;
        $approveSum = 0;
        foreach($request->voteData as $voter=>$vote) {
            if($vote == 1) $rejectSum += 1;
            if($vote == 2) $approveSum += 1;
        }
    ?>
    <div class="card mb-3"><div class="card-body">
        <h5 class="text-left">{{$request->status == 'Pending' ? 'Vote' : 'Past Votes'}} on this {{ $request->update_type == 'MYO' ? 'MYO Submission' : 'Design Update' }}
        @if($request->status == 'Pending')
            <span class="text-right float-right">
                <div class="row">
                    <div class="col-sm-6 text-center text-danger">
                        {{ $rejectSum }}/{{ Settings::get('design_votes_needed') }}
                        {!! Form::open(['url' => 'admin/designs/vote/'.$request->id.'/reject', 'id' => 'voteRejectForm']) !!}
                            <button class="btn {{ $request->voteData->get(Auth::user()->id) == 1 ? 'btn-danger' : 'btn-outline-danger' }}" style="min-width:40px;" data-action="reject"><i class="fas fa-times"></i></button>
                        {!! Form::close() !!}
                    </div>
                    <div class="col-sm-6 text-center text-success">
                        {{ $approveSum }}/{{ Settings::get('design_votes_needed') }}
                        {!! Form::open(['url' => 'admin/designs/vote/'.$request->id.'/approve', 'id' => 'voteApproveForm']) !!}
                            <button class="btn {{ $request->voteData->get(Auth::user()->id) == 2 ? 'btn-success' : 'btn-outline-success' }}" style="min-width:40px;" data-action="approve"><i class="fas fa-check"></i></button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </span>
        @endif
        </h5>
            <p>
                {{ $request->update_type == 'MYO' ? 'MYO Submissions' : 'Design updates' }} need {{ Settings::get('design_votes_needed') }} votes before they are considered approved. Note that this does not automatically process the submission in any case, only indicate a consensus.
            </p>
        <hr/>
        @if(isset($request->vote_data) && $request->vote_data)
            <h4>Votes:</h4>
                <div class="row">
                    <div class="col-md">
                        <h5>Reject:</h5>
                        <ul>
                        @foreach($request->voteData as $voter=>$vote)
                            @if($vote == 1)
                            <li>
                                {!! App\Models\User\User::find($voter)->displayName !!} {{ $voter == Auth::user()->id ? '(you)' : '' }}
                            </li>
                            @endif
                        @endforeach
                        </ul>
                    </div>
                    <div class="col-md">
                        <h5>Approve:</h5>
                        <ul>
                        @foreach($request->voteData as $voter=>$vote)
                            @if($vote == 2)
                            <li>
                                {!! App\Models\User\User::find($voter)->displayName !!} {{ $voter == Auth::user()->id ? '(you)' : '' }}
                            </li>
                            @endif
                        @endforeach
                        </ul>
                    </div>
                </div>
        @else
            <p>No votes have been cast yet!</p>
        @endif
    </div></div>
@endif

<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a class="nav-link {{ set_active('designs/' . $request->id) }}" href="{{ url('designs/' . $request->id) }}">@if($request->is_complete)<i class="text-success fas fa-check-circle fa-fw mr-2"></i> @endif Status</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ set_active('designs/' . $request->id . '/comments') }}" href="{{ url('designs/' . $request->id . '/comments') }}"><i class="text-{{ $request->has_comments ? 'success far fa-circle' : 'danger fas fa-times'  }} fa-fw mr-2"></i> Comments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ set_active('designs/' . $request->id . '/image') }}" href="{{ url('designs/' . $request->id . '/image') }}"><i class="text-{{ $request->has_image ? 'success far fa-circle' : 'danger fas fa-times'  }} fa-fw mr-2"></i> Masterlist Image</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ set_active('designs/' . $request->id . '/addons') }}" href="{{ url('designs/' . $request->id . '/addons') }}"><i class="text-{{ $request->has_addons ? 'success far fa-circle' : 'danger fas fa-times'  }} fa-fw mr-2"></i> Add-ons</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ set_active('designs/' . $request->id . '/traits') }}" href="{{ url('designs/' . $request->id . '/traits') }}"><i class="text-{{ $request->has_features ? 'success far fa-circle' : 'danger fas fa-times'  }} fa-fw mr-2"></i> Traits</a>
    </li>
</ul>

resources/views/character/design/_sidebar.blade.php
<ul>
    @if(isset($request))
        <li class="sidebar-section">
            <div class="sidebar-section-header">Current Request</div>
            <div class="sidebar-item"><a href="{{ $request->url }}" class="{{ set_active('designs/'.$request->id) }}">View</a></div>
            <div class="sidebar-item"><a href="{{ $request->url . '/comments' }}" class="{{ set_active('designs/' . $request->id . '/comments') }}">Comments</a></div>
            <div class="sidebar-item"><a href="{{ $request->url . '/image' }}" class="{{ set_active('designs/' . $request->id . '/image') }}">Image</a></div>
            <div class="sidebar-item"><a href="{{ $request->url . '/addons' }}" class="{{ set_active('designs/' . $request->id . '/addons') }}">Add-ons</a></div>
            <div class="sidebar-item"><a href="{{ $request->url . '/traits' }}" class="{{ set_active('designs/' . $request->id . '/traits') }}">Traits</a></div>
        </li>
    @endif
    <li class="sidebar-section">
        <div class="sidebar-section-header">Design Approvals</div>
        <div class="sidebar-item"><a href="{{ url('designs') }}" class="{{ set_active('designs') }}">Drafts</a></div>
        <div class="sidebar-item"><a href="{{ url('designs/pending') }}" class="{{ set_active('designs/*') }}">Submissions</a></div>
    </li>
</ul>

resources/views/character/design/addons.blade.php
@extends('character.design.layout')

@section('design-title') Design Approval Request (#{{ $request->id }}) :: Comments @endsection

@section('design-content')
{!! breadcrumbs(['Design Approvals' => 'designs', 'Request (#' . $request->id . ')' => 'designs/' . $request->id, 'Comments' => 'designs/' . $request->id . '/comments']) !!}

@include('character.design._header', ['request' => $request])

<h2>Add-ons</h2>

@if($request->status == 'Draft' && $request->user_id == Auth::user()->id && $request->character)
    <p>Select items and/or currency to add onto your request. These items will be removed from your inventory{{ $request->character->is_myo_slot ? '' : ' and/or character' }} but refunded if removed from the request, the request is rejected, or the request is deleted. If you don't intend to attach any items/currency, click the Save button once to mark this section complete regardless.</p>
    {!! Form::open(['url' => 'designs/'.$request->id.'/addons']) !!}
        @include('widgets._inventory_select', ['user' => Auth::user(), 'inventory' => $inventory, 'categories' => $categories, 'selected' => $request->inventory])
        @include('widgets._bank_select', ['owner' => Auth::user(), 'selected' => $request->userBank])

        @if(!$request->character->is_myo_slot)
            @include('widgets._bank_select', ['owner' => $request->character, 'selected' => $request->characterBank])
        @endif

        <div class="text-right">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        </div>
    {!! Form::close() !!}
@else
    <p>Items and/or currency listed have been removed from their holders and will be refunded if the request is rejected.</p>
    @if($inventory && count($inventory))
        <h3>{!! $request->user->displayName !!}'s Inventory</h3>
        <div class="card mb-3">
            <div class="card-body">
                <table class="table table-sm">
                    <thead class="thead-light">
                        <tr class="d-flex">
                            <th class="col-2">Item</th>
                            <th class="col-4">Source</th>
                            <th class="col-4">Notes</th>
                            <th class="col-2">Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($inventory['user_items'] as $itemRow)
                            <tr class="d-flex">
                                <td class="col-2">@if(isset($items[$itemRow['asset']->item_id]->image_url)) <img class="small-icon" src="{{ $items[$itemRow['asset']->item_id]->image_url }}" alt=" {{ $items[$itemRow['asset']->item_id]->name }} "> @endif {!! $items[$itemRow['asset']->item_id]->name !!}
                                <td class="col-4">{!! array_key_exists('data', $itemRow['asset']->data) ? ($itemRow['asset']->data['data'] ? $itemRow['asset']->data['data'] : 'N/A') : 'N/A' !!}</td>
                                <td class="col-4">{!! array_key_exists('notes', $itemRow['asset']->data) ? ($itemRow['asset']->data['notes'] ? $itemRow['asset']->data['notes'] : 'N/A') : 'N/A' !!}</td>
                                <td class="col-2">{!! $itemRow['quantity'] !!}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif
    @if(count($request->userBank))
        <h3>{!! $request->user->displayName !!}'s Bank</h3>
        <table class="table table-sm mb-3">
            <thead>
                <tr>
                    <th width="70%">Currency</th>
                    <th width="30%">Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach($request->getBank('user') as $currency)
                    <tr>
                        <td>{!! $currency->displayName !!}</td>
                        <td>{{ $currency->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif
    @if($request->character && count($request->characterBank))
        <h3>{!! $request->character->displayName !!}'s Bank</h3>
        <table class="table table-sm mb-3">
            <thead>
                <tr>
                    <th width="70%">Currency</th>
                    <th width="30%">Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach($request->getBank('character') as $currency)
                    <tr>
                        <td>{!! $currency->displayName !!}</td>
                        <td>{{ $currency->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif
@endif

@endsection

@section('scripts')
    @include('widgets._bank_select_row', ['owners' => [Auth::user(), $request->character]])
    @include('widgets._inventory_select_js', ['readOnly' => true])
    @include('widgets._bank_select_js', [])
@endsection